title: 'Generated'
key: C4
bpm: 80
defaultNoteGroup: 4
shift: 0

%%
1v7v5x
vv7v6v5-
-v5v5-
v4#v6v4#-
---x
v1v1v2-
v1--v1
vv7vv7v2v6
v5--x
1v7v5v3
v3-v5vv7
v2-v1x
v2v3--
---x
v3v5v4#v6
v5--x
v61v5v1
vv7xxv6
---x
xv3v4#-
---x
vv7vv7vv7vv6
--v3v5
v4v4#v5-
v6--x
xv2v1-
----
xv3v3v1
---x
xv3v2-
vv7vv7-v1
-vv7vv6-
-v1--
---v1
v1v1v4#v5
v6v4#-x
xv5v4#v3
---v1
v2v1v2v2
v1v1vv7vv7
