title: 'Jazz Progressions'
key: C4
bpm: 60
defaultNoteGroup: 4
shift: 0
tonicPickup: true

%%
[I-ii-iii-IV]
1234
xxxx

[I-IV-ii-V]
1425
xxxx

[I-iii-vi-IV]
1364
xxxx

[ii-IV-I-V]
2415
xxxx

[iii-IV-I-V]
3415
xxxx

[IV-I-V-vi]
4156
xxxx

[I-V-ii-vi]
1526
xxxx

[vi-ii-V-I]
6251
xxxx

[iii-vi-ii-V]
3625
xxxx

[ii-V-I]
251x
xxxx

[ii-V-I-vi]
2516
xxxx

[ii-V-I-IV]
2514
xxxx

[IV-ii-V-I]
4251
xxxx

[vi-IV-ii-V]
6425
xxxx

[I-vi-ii-V]
1625
xxxx

[I-vi-IV-V]
1645
xxxx

[I-iii-IV-V]
1345
xxxx

[I-IV-V-vi]
1456
xxxx

[I-V-vi-IV]
1564
xxxx

[IV-V-I-vi]
4516
xxxx

[ii-IV-V-I]
2451
xxxx

[V-IV-ii-I]
5421
xxxx

[vi-V-IV-I]
6541
xxxx

[vi-V-IV-ii]
6542
xxxx

[IV-iii-ii-I]
4321
xxxx

[V-IV-iii-ii]
5432
xxxx

[I-vii-vi-V]
1765
xxxx

[IV-V-vi-iii]
4563
xxxx

[I-ii-IV-V]
1245
xxxx

[ii-iii-IV-V]
2345
xxxx

[IV-V-vi-vii]
4567
xxxx

[vi-V-iii-IV]
6534
xxxx

[I-vii-ii-V]
1725
xxxx

[iii-ii-V-I]
3251
xxxx

[IV-iii-vi-ii]
4362
xxxx

[V-vi-ii-V]
5625
xxxx

[IV-vii-iii-vi-ii-V-I]
4736
251x
xxxx

[vi-ii-V-I-IV-vii-iii]
6251
473x
xxxx

[I-IV-vii-iii-vi-ii-V]
1473
625x
xxxx

[iii-vi-ii-V-I-vi]
3625
16xx
xxxx

[I-vi-IV-ii-V-I]
1642
51xx
xxxx

[I-vi-ii-V-I-vi-ii-V]
1625
1625
xxxx

[iii-vi-ii-V-I-vi-ii-V]
3625
1625
xxxx

[I-IV-ii-V-I-vi-ii-V]
1425
1625
xxxx

[vi-ii-V-I-IV-V-I-vi]
6251
4516
xxxx

[iii-vi-ii-V-I-IV-V-I]
3625
1451
xxxx

[I-iii-vi-IV-ii-V-I-V]
1364
2515
xxxx

[IV-V-iii-vi-ii-V-I-I]
4536
2511
xxxx

[I-iii-vi-ii-V-IV-I-V]
1362
5415
xxxx

[ii-V-I-iii-vi-ii-V-I]
2513
6251
xxxx

[I-vi-iii-vii-IV-ii-V-I]
1637
4251
xxxx

[IV-iii-vi-ii-V-IV-I-V]
4362
5415
xxxx

[vi-V-IV-ii-V-I-IV-I]
6542
5141
xxxx

[12-bar blues]
1111
4411
5411
xxxx

[jazz blues]
1411
4411
5451
xxxx

[blues quick change]
1411
4416
2511
xxxx

[blues with turnaround]
1111
4416
2516
xxxx

[blues shuffle]
1141
4415
1541
xxxx

[minor blues feel]
1111
4411
1516
xxxx
