title: 'Progression Study'
key: C4
bpm: 60
defaultNoteGroup: 4
shift: 0
tonicPickup: true

%%
[I-V-vi-IV]
1564
xxxx

[I-vi-IV-V]
1645
xxxx

[I-V-vi-iii-IV-I-IV-V]
1563
4145
xxxx

[iii-vi-IV-V]
3645
xxxx

[vi-IV-I-V]
6415
xxxx

[I-vi-ii-V]
1625
xxxx

[ii-V-I-vi]
2516
xxxx

[I-IV-V-I]
1451
xxxx

[vi-IV-V-I]
6451
xxxx

[IV-V-iii-vi-ii-V-I]
4536
251x
xxxx

[ii-V-I]
251x
xxxx

[IV-V-iii-vi-IV-iii-vi]
4536
436x
xxxx
