title: 'Rock Progressions'
key: C4
bpm: 60
defaultNoteGroup: 4
shift: 0
tonicPickup: true

%%
[I-IV-I-V]
1415
xxxx

[I-V-IV-V]
1545
xxxx

[I-I-IV-V]
1145
xxxx

[vi-V-IV-V]
6545
xxxx

[I-IV-I-IV]
1414
xxxx

[I-iii-IV-V]
1345
xxxx

[IV-V-I-vi]
4516
xxxx

[vi-V-IV-III]
6543
xxxx

[I-iii-ii-V]
1325
xxxx

[IV-I-ii-V]
4125
xxxx

[I-IV-V-IV]
1454
xxxx

[I-V-IV-I]
1541
xxxx
